### ISSUE TITLE
Does not work with Brave Shields

### ISSUE THREAD

**Issue by mustafahasankhan** [yutro/adblock-detector#10]
Using in NextJS.

**Comment by yutro** [comment]
Hi, thanks for reaching out. Could you give a bit more info what is 'Brave Shields' or mb you have steps to reproduce :) 
mb you have code sandbox example or something, which could help me to reproduce issue :) so i could fix it :)

**Comment by mustafahasankhan** [comment]
Hey,
Brave shields refer to the ad and trackers blocking mechanism used in Brave browser.
To reproduce just try to open any page in Brave browser.

**Comment by yutro** [comment]
hi :) i think your issue is related to this https://github.com/yutro/adblock-detector/issues/6 (i think next.js does the same)

**Comment by bappyasif** [comment]
> hi :) i think your issue is related to this #6 (i think next.js does the same)

i have also tried with "firefox", same results!!.... after looking at your attached issue link, solution that you provided was to "rollup", how do i do that for "nextjs app" using "create nextjs app" command

thanks and happy coding :)

**Comment by yutro** [comment]
sorry for late response, dunno how to tweak nextjs cause i don't use it 😄
